# 등록
POST http://127.0.0.1:8080/redis/template
Content-Type: application/json

{
  "key": "N1000",
  "value": "안녕하세요. 좋은 밤이예요."
}

###

# 조회
GET http://127.0.0.1:8080/redis/template/N1000

###

# 삭제
DELETE http://127.0.0.1:8080/redis/template/N1000

###